[package]
name = "reading_list"
version = "0.1.0"
edition = "2021"

[features]
default = []
inspect = ["wasm-logger"]

[dependencies]
serde = "1"
serde_json = "1"
yew-hooks = "0.2.0"
yew-router = "0.17.0"
yew = { version = "0.20.0", features = ["csr"] }
wasm-logger = { version = "0.2.0", optional = true }
